"""
Core data models for the PDF/Image -> CSV invoice extraction pipeline.

Design notes:
- Every Job carries a user_id from day one, even before real auth exists,
  so ownership/visibility scoping doesn't need to be retrofitted later.
- InvoiceGroup.source_page_list is a list (not just start/end) because
  groups can be non-contiguous (see merge-on-repeat-invoice-number logic).
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class JobStatus(str, Enum):
    UPLOADED = "uploaded"
    QUEUED = "queued"
    PROCESSING = "processing"
    REVIEW_REQUIRED = "review_required"
    READY_TO_EXPORT = "ready_to_export"
    EXPORTED = "exported"
    FAILED = "failed"
    CANCELLED = "cancelled"


class SupportedFileType(str, Enum):
    PDF = "pdf"
    JPEG = "jpeg"
    PNG = "png"
    WEBP = "webp"


class ConfidenceBand(str, Enum):
    HIGH = "high"       # >= 0.90 starting threshold
    REVIEW = "review"   # 0.75 - 0.89
    LOW = "low"         # < 0.75
    NOT_FOUND = "not_found"


class SplitRange(BaseModel):
    """A single user-entered page range, e.g. '4-6' or '10'."""
    start_page: int = Field(..., ge=1)
    end_page: int = Field(..., ge=1)

    def contains(self, page_number: int) -> bool:
        return self.start_page <= page_number <= self.end_page


class SplitValueInput(BaseModel):
    """
    Raw split value as entered by the user, e.g. "1-3, 4-6, 7-9" or "5" or None.
    Parsing/validation happens in services/split_parser.py.
    """
    raw_value: Optional[str] = None


class InvoiceLineItem(BaseModel):
    line_number: int
    item_description: str
    hsn_sac: Optional[str] = None
    # Pharma-format fields (see native_pdf_extraction.py's pharma column
    # mapping). batch_number/expiry_date are regulatory-required for
    # pharma distribution, not present on the earlier generic invoice format.
    batch_number: Optional[str] = None
    expiry_date: Optional[str] = None
    quantity: Optional[float] = None  # generic quantity, used by non-pharma formats
    # Confirmed with client: Sold and Free quantities for the same product
    # are kept as SEPARATE line items (separate rows, as printed), not
    # merged into one row -- a given pharma-format row populates whichever
    # one of these three matches its own Sold/Free/Total sub-column, not all three.
    quantity_sold: Optional[float] = None
    quantity_free: Optional[float] = None
    quantity_total: Optional[float] = None
    uom: Optional[str] = None
    unit_rate: Optional[float] = None
    mrp: Optional[float] = None  # Maximum Retail Price (regulatory ceiling price)
    ptr: Optional[float] = None  # Price To Retailer (the rate actually billed)
    # Price To Stockist -- confirmed against a real invoice that pairs a
    # "PTR"/"PTS" column with no "Rate" wording at all (see rate_pts's
    # keyword list in native_pdf_extraction.py); previously captured under
    # this same field name as an unconfirmed guess, kept as-is here to
    # avoid an API/CSV column rename.
    rate_pts: Optional[float] = None
    taxable_value: Optional[float] = None
    # Real invoices commonly print BOTH a per-line discount rate (%) and
    # the resulting discount amount as separate columns -- same rate/amount
    # split already used for CGST/SGST/IGST below.
    discount_rate: Optional[float] = None
    discount_amount: Optional[float] = None  # per-line discount; distinct from the header-level one
    cgst_rate: Optional[float] = None
    cgst_amount: Optional[float] = None
    sgst_rate: Optional[float] = None
    sgst_amount: Optional[float] = None
    igst_rate: Optional[float] = None
    igst_amount: Optional[float] = None
    line_total: Optional[float] = None
    source_page: Optional[int] = None
    field_confidences: dict[str, ConfidenceBand] = Field(default_factory=dict)


class InvoiceGroup(BaseModel):
    """
    One detected invoice within an uploaded file. May span non-contiguous
    pages if the same invoice number reappears later in the document
    (see merge logic in services/invoice_grouping.py).

    invoice_number: for the confirmed pharma/GST invoice format, this is
    specifically the IRN (Invoice Reference Number) -- a 64-character hex
    string generated by the GST e-invoice system, NOT a vendor-assigned
    number. See native_pdf_extraction.py's IRN-shape confidence check.

    header_fields / header_field_confidences stay a loose dict rather than
    explicit typed columns (deliberate -- see native_pdf_extraction.py for
    why), but the canonical keys populated by the pharma extraction path
    are documented here for discoverability:
        invoice_number       - the IRN (see above)
        invoice_date, ack_number, eway_bill_number, eway_bill_date,
        fssai_number          - all optional strings, frequently blank
        party_name, party_gstin
                               - the VENDOR/SELLER (found via the
                                 "FOR <company>" signature line), not the buyer
        buyer_name, buyer_address
                               - the BUYER (Bill To / M/s / Customer), distinct
                                 from party_name/party_gstin above
        subtotal_taxable, total_amount, discount_amount, tcs_amount,
        invoice_amount, adjustment_amount, invoice_total
                               - invoice_total holds the final/net-payable
                                 figure; the others are the individual steps
                                 of the totals block, kept separate (no
                                 consolidation)
        tax_bracket_summary   - list[{"rate", "taxable_amount", "tax_amount"}],
                                 the invoice-level GST rate-wise breakup;
                                 kept separate from per-line-item tax fields
    """
    group_id: UUID = Field(default_factory=uuid4)
    invoice_number: Optional[str] = None
    invoice_number_confidence: ConfidenceBand = ConfidenceBand.NOT_FOUND
    source_page_list: list[int] = Field(default_factory=list)
    is_non_contiguous_merge: bool = False  # flags "confirm this merge" in preview UI
    header_fields: dict = Field(default_factory=dict)
    header_field_confidences: dict[str, ConfidenceBand] = Field(default_factory=dict)
    line_items: list[InvoiceLineItem] = Field(default_factory=list)
    needs_user_review: bool = True


class ExportedFile(BaseModel):
    """Metadata for one persisted export artifact (a per-invoice CSV or the
    job's zip archive), recorded so it can be served again without
    regenerating it -- see services/export_storage.py and csv_export.py."""
    filename: str
    file_path: str
    size_bytes: int
    sha256_checksum: str


class JobExportMetadata(BaseModel):
    """
    Recorded on a Job once its export artifacts have been generated.
    invoice_files is keyed by InvoiceGroup.group_id (as a string) rather
    than invoice_number, since invoice_number is not guaranteed unique
    within a job -- the same number can appear in two separate groups when
    split-range hard-fencing is in play (see invoice_grouping.py).
    """
    invoice_files: dict[str, ExportedFile] = Field(default_factory=dict)
    zip_file: Optional[ExportedFile] = None
    generated_at: Optional[datetime] = None


class Job(BaseModel):
    job_id: UUID = Field(default_factory=uuid4)
    user_id: str  # placeholder until real auth lands; every job is owned by someone
    original_filename: str
    file_type: SupportedFileType
    page_count: Optional[int] = None
    split_value_raw: Optional[str] = None
    split_ranges: list[SplitRange] = Field(default_factory=list)
    status: JobStatus = JobStatus.UPLOADED
    invoice_groups: list[InvoiceGroup] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    error_message: Optional[str] = None
    export: Optional[JobExportMetadata] = None


class JobSummary(BaseModel):
    """Lightweight shape for the History screen listing."""
    job_id: UUID
    original_filename: str
    status: JobStatus
    invoice_count: int
    created_at: datetime
    updated_at: datetime
